### ISSUE TITLE
Remove non-inherent dependency on Jaxcore

### ISSUE THREAD

**Issue by benbucksch** [jaxcore/bumblebee-hotword-node#2]
BumbleBee node depends on jaxcore. Jaxcore is a large package, which itself again depends on many other packages. Actually, Jaxcore is not even declared as dependency in package.json, so it seems rather accidental.

But BumbleBee seems to need only the relatively small `Jaxcore.Service` class and a related class, and the logger.

I would recommend to break these dependencies into their own npm modules, and depend only on these. This would allow BumbleBee to be used in contexts outside of Jaxcore, which probably was the goal of the module.

**Comment by dsteinman** [comment]
I've just made these changes in the master branch.  Please check and I'll publish 0.0.5 to npm.

**Comment by benbucksch** [comment]
Thank you!

Yes, I verified that  0.0.4 fails to run without jaxcore dependency, and 0.0.5 works without jaxcore dependency. VERIFIED FIXED.

Thanks! :)

**Comment by dsteinman** [comment]
Cool, I just published it.
