### ISSUE TITLE
pcm-convert fails on RPI 3

### ISSUE THREAD

**Issue by kopiro** [jaxcore/bumblebee-hotword-node#6]
Everything works fine on OSX, but when I tested this on RPI3, I have this error from `pcm-convert`:

```
Jul 23 00:34:07 KoPi start-home.sh[7672]: /home/pi/Desktop/Otto/node_modules/pcm-convert/index.js:103
Jul 23 00:34:07 KoPi start-home.sh[7672]:                 src = new (dtypeClass[from.dtype])(src)
Jul 23 00:34:07 KoPi start-home.sh[7672]:                       ^
Jul 23 00:34:07 KoPi start-home.sh[7672]: RangeError: byte length of Int16Array should be a multiple of 2
Jul 23 00:34:07 KoPi start-home.sh[7672]:     at new Int16Array (<anonymous>)
Jul 23 00:34:07 KoPi start-home.sh[7672]:     at convert (/home/pi/Desktop/Otto/node_modules/pcm-convert/index.js:103:9)
Jul 23 00:34:07 KoPi start-home.sh[7672]:     at Socket.<anonymous> (/home/pi/Desktop/Otto/node_modules/bumblebee-hotword-node/lib/bumblebee-node.js:152:22)
Jul 23 00:34:07 KoPi start-home.sh[7672]:     at Socket.emit (events.js:315:20)
Jul 23 00:34:07 KoPi start-home.sh[7672]:     at Socket.EventEmitter.emit (domain.js:485:12)
Jul 23 00:34:07 KoPi start-home.sh[7672]:     at addChunk (_stream_readable.js:297:12)
Jul 23 00:34:07 KoPi start-home.sh[7672]:     at readableAddChunk (_stream_readable.js:273:9)
Jul 23 00:34:07 KoPi start-home.sh[7672]:     at Socket.Readable.push (_stream_readable.js:214:10)
Jul 23 00:34:07 KoPi start-home.sh[7672]:     at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
Jul 23 00:34:07 KoPi start-home.sh[7672]: error Command failed with exit code 1.
```

I'm using the default `bumblebee` hotword and the basic example :)

Happy to help you in any way.

**Comment by dsteinman** [comment]
`RangeError: byte length of Int16Array should be a multiple of 2`

That's weird.  I wonder if there is any data at all coming from the `sox`, maybe there are no bytes at all.  Does the script have read access to both sox and the microphone device?

I do have a rpi3 I can test with, I'll see if I can reproduce the error.

**Comment by dsteinman** [comment]
I switched the command line program that linux uses back to `rec` instead of `sox`, this works on Linux/x64 but haven't tried a pi3 yet.

https://github.com/jaxcore/bumblebee-hotword-node/commit/02b9c00f70a2f6c3652407cb51f659a964f91e2e

**Comment by kopiro** [comment]
I'll try by checking master

**Comment by Patronics** [comment]
I can confirm this fix works, at least on a Raspberry Pi 4. Also bumblebee-deepspeech's examples are still configured to use an older version of bumblebee-hotword-node that doesn't have the fix. You can expect a pull request to fix that to be coming in soon :)
