### ISSUE TITLE
No way to set device

### ISSUE THREAD

**Issue by ncpleslie** [jaxcore/bumblebee-hotword-node#7]
There is currently no way to set the device.
E.g. If I wanted to set the recording device to `plughw:1,0`, etc.

The following code in `bumble-node.js` after line 118 will add this feature. 

`
	let device;
	if (this.options && this.options.device) {
		device = this.options.device;
	}
`
`
	this.recorder = new AudioRecorder({
		device,
		program,
		silence: 0,
		paths: this.options ? this.options.paths : null
	});
`

https://github.com/ncpleslie/bumblebee-hotword-node/blob/master/lib/bumblebee-node.js

This could also be the reason why it closes for some users #4 #3 
Failing to set a device on a Linux computer will just closeout. 
I've tested this fix on a Raspbian where I've used node-audiorecorder in a few other places and can confirm it works correctly. 

If you want, I can make a pull request to remedy this issue.

**Comment by dsteinman** [comment]
Okay great, I added the lines here:

https://github.com/jaxcore/bumblebee-hotword-node/commit/14dd0e5301f756e68c20b4a8846588f004020c9e

Can you confirm this works, and I'll republish it?

**Comment by ncpleslie** [comment]
Yip. Works for me.

Tested on a Raspberry Pi 4 running Raspbian and passing `plughw:2,0` through. 

I used `"bumblebee-hotword-node": "https://github.com/jaxcore/bumblebee-hotword-node/tarball/master"`

Thanks for the update and the awesome project

**Comment by dsteinman** [comment]
Great, thanks for the help.  That's been published as v0.1.1
