### ISSUE TITLE
Creating custom hotword not functioning

### ISSUE THREAD

**Issue by SteTR** [jaxcore/bumblebee-hotword-node#8]
Hello, 
I'm trying to create a custom hotword for my project but I can't seem to get it to work. I've tried using the three options: Windows, Mac, and Linux; and I suspect that these aren't support in bumblebee-hotword-node. Is WASM only supported for this project? 
If that's the case, that's unfortunate since the only way to produce WASM ppn files is through a commercial license.

**Comment by dsteinman** [comment]
No unfortunately this code doesn't use the native keywords.  Picovoice themselves don't even provide a NodeJS library.

It would probably be possible to write a NodeJS binding using the precompiled C shared library that Picovice supplies:

https://github.com/Picovoice/porcupine/tree/master/demo/c

I really don't know enough C to do this myself though.

**Comment by SteTR** [comment]
That's unfortunate. Well it's not really an issue so closing it.
